# Literature

Here is a review of existing methods.

## Housing and Health

The link between housing and health is extensive and well documented. Occupants of a home are exposed to biologic, chemical, and physical agents that can affect their health and safety [@cdc2006 63] . For instance, paint containing lead is known to cause childhood lead poisoning, which lead to the a ban on lead-based paint for residential use in 1978 [@cdc2020].

Asthma, a respiratory disease which causes episodes of wheezing, breathlessness, chest tightness, and coughing, has been linked to exposure to mold or dampness and pests including dust mites, cockroaches, and rodents [@cdc2006 63].

Reviewing the existing literature, @mendell2011 found dampness inside homes was linked to a wide range of respiratory or allergic health effects, including asthma. The authors concluded that prevention and remediation to reduce indoor dampness is urgently needed in a large proportion of the building stock, and such measures could significantly reduce the prevalence of respiratory and allergic disease. @rauh2002 found that cockroach allergen levels are related to the degree of household disrepair, and similarly suggested that public health interventions in housing could reduce allergen exposure.

In 2015, the Asthma and Allergy Foundation of America named Memphis the asthma capital of America [@aafa2015], based on prevalence, risk factors, and medical factors. Recent efforts to reduce the prevalence and risk of asthma have been successful---Memphis's rank has since decreased to 41st in 2021 [@aafa2021].[^literature-1] However, Memphis still ranks high in asthma-related mortality, placing 7th of 100 cities.

[^literature-1]: The ranking method changed between 2015 and 2021, with fewer factors involved in a city's overall ranking in 2021.

A recent study in Memphis comparing pediatric asthma data with property quality information found that asthma prevalence is disproportionately distributed throughout the city [@shin2018]. Neighborhood blight and inequality were closely associated with childhood asthma and other health problems, leading authors to conclude that effective health interventions should consider involving housing policies and procedures.

Households can take certain steps to reduce health risks, such as decreasing allergens by removing pets from the home and frequent dusting and vacuuming. However, risks caused by larger structural issues can be difficult to implement, particularly for low-income households that rent, as tenants have little or no power to repair such problems. A study of low-income parents of children with asthma found landlords were directly involved in keeping homes in poor condition, even when asked by the tenant to fix the property, and a cycle of fear, poverty, and lack of power compounded to make tenants hesitant to report problems [@grineski2010]. Relocating families can reduce health risks, but higher rents associated with safer housing can make it financially difficult or impossible for some families to move [@mclaine2006].

Current regulation of private rental housing quality assumes that tenants will take action to report substandard housing, yet this is often not the case. To understand the disconnect between the law's expectations and reality, @chisholm2018 collected existing qualitative literature to explore power dynamics in the landlord-tenant relationship. The research showed that, for the most part, tenants who "reported housing quality problems found it a stressful experience, with repairs taking a long time to be carried out, or not at all." This experience often impacted future behavior, causing tenants to avoid reporting problems because they did not think it would be effective.

In some cases, tenants would rather move out than work towards a resolution, leaving the issue open for future tenants. In other instances, tenants with low incomes were aware of the lack of alternative housing, causing them to remain silent. Fear of eviction prevented tenants from reporting problems, and this fear was not unfounded; in three of the 15 studies, tenants who reported housing problems were evicted or forced to move. Though laws against retaliatory action might exist, no-cause evictions allow landlords to still remove the tenant from the unit. @chisholm2018 concludes that tenants do not report housing quality problems because the regulation that relies on their reporting fails to protect many tenants.

A wide range of solutions are put forward to improve tenant reporting. Ending no-cause evictions and expanding legal aid can encourage tenants who may have been scared to speak up. Increasing the supply of social or public housing can expand housing options to households most vulnerable to changes in rent. The authors also suggest authorities supervise a web-based reporting system for repair requests, establishing clear records, automated reminders to the landlords, and an opportunity for authorities to step in for unduly slow repairs.

## Code Enforcement
