# Data: Memphis Housing Quality

## American Housing Survey

Data on housing quality in the Memphis MSA is available through the [American Housing Survey](https://www.census.gov/programs-surveys/ahs.html).

When surveyed on the adequacy of their housing, 14.5% of renter-occupied units were thought of as inadequate, compared to 10% of owner-occupied units. This disparity in quality between renter- and owner-occupied households is significant when we compare specific housing problems, as shown in the tables below.[^memphis-1]

[^memphis-1]: In the discussions below, "renters" refers to renter-occupied units, "owners" refers to owner-occupied units, and "Memphis" refers to the Memphis MSA.

### Selected Housing Deficiencies

+-----------------------------------------------------+----------+-----------+---+---------+-----------+
|                                                     | **Rent** |           |   | **Own** |           |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| **Deficiency**                                      | **Est**  | **Pct**   |   | **Est** | **Pct**   |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| Signs of cockroaches in last 12 months              | 50.9     | **22.7%** |   | 44.4    | 15.3%     |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| Signs of mice or rats inside home in last 12 months | 24.4     | 10.9%     |   | 32.6    | **11.3%** |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| Open cracks or holes (interior)                     | 14.4     | **6.4%**  |   | 12.1    | 4.2%      |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| Rooms without electric outlets                      | 6.6      | **2.9%**  |   | 5.0     | 1.7%      |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| Broken plaster or peeling paint (interior)          | 5.3      | **2.4%**  |   | 5.8     | 2.0%      |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| Exposed wiring                                      | 3.9      | **1.7%**  |   | 4.5     | 1.6%      |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+
| Total housing units                                 | 224.0    | \-        |   | 289.7   | \-        |
+-----------------------------------------------------+----------+-----------+---+---------+-----------+

: Source: [American Housing Survey](https://www.census.gov/newsroom/press-releases/2020/2019-american-housing-survey.html) (2019). Estimates in thousands of housing units.

Renter-occupied units experienced more housing deficiencies than owner-occupied units for all but one of the selected problems.

Pests are prevalent in both owner and renter-occupied units. Renters saw more signs of cockroaches (by 7.4 percentage points), while owners were more likely to sight mice or rats (by 0.4 percentage points). These trends align with national data, where renters were 1.98 times more likely to see cockroaches and owners were 1.17 times more likely to report a rodent sighting [@sellner2021]. Compared to national averages, housing units in the Memphis MSA saw slightly fewer rodents (11.1% vs 11.9%) and significantly more cockroaches (18.6% vs. 11.3%).

Renters were moderately more likely to have open cracks or holes in the interior of their home and to have rooms without electrical outlets. They were also slightly more likely to have decaying interior walls and exposed wiring.

### Housing Problems

The following table shows the number of units who experience selected housing problems. An estimate of "S" denotes a sample too small to meet publication standards or avoid disclosure of identifying information. The total column ("Tot") is the number of housing units *capable* of experiencing each problem (rather than all housing units). For instance, the total number of units with heating problems only includes units with heating equipment who occupied their unit last winter (excluding units without heating equipment or those who did not occupy their unit last winter).

+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
|                                                    |         | **Rent** |          |   |         | **Own** |          |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| **Problem**                                        | **Est** | **Tot**  | **Pct**  |   | **Est** | **Tot** | **Pct**  |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| No flush toilet working some time in last 3 months | 7.0     | 224.0    | **3.1%** |   | S       | 289.7   | \-       |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| Uncomfortably cold for 24 hours or more            | 12.3    | 186.2    | **6.6%** |   | 10.8    | 278.8   | 3.9%     |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| Fuses or breakers blown in last 3 months           | 14.1    | 223.8    | 6.3%     |   | 19.3    | 289.7   | **6.7%** |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| Water stoppage in last 3 months                    | 6.4     | 223.8    | **2.9%** |   | 3.2     | 289.5   | 1.1%     |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| Water leakage from inside structure                | 19.5    | 224.0    | **8.7%** |   | 20.7    | 289.7   | 7.1%     |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| Water leakage from outside structure               | 18.9    | 224.0    | 8.4%     |   | 25.5    | 289.7   | **8.8%** |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| Mold in last 12 months                             | 11.8    | 224.0    | **5.3%** |   | 5.8     | 289.7   | 2.0%     |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+
| Public sewer breakdown in last 3 months            | 5.1     | 217.9    | **2.3%** |   | S       | 252.3   | \-       |
+----------------------------------------------------+---------+----------+----------+---+---------+---------+----------+

: Source: [American Housing Survey](https://www.census.gov/newsroom/press-releases/2020/2019-american-housing-survey.html) (2019). Estimates in thousands of housing units.

Renter-occupied units were overall more likely to experience housing problems and breakdowns than owner-occupied units.

The most common problem for renters and owners was water leakage during the past year. Owners were slightly more likely (by 0.4 percentage points) to experience leakage from outside the structure, such as from the roof, walls, closed windows, or doors. Renters were more likely (by 1.6 percentage points) to experience internal water leakage, such as from a leaky pipe, a broken water heater, or a backed up or overflown fixture. This is likely why renters were more likely to report mold growth within the past year (by 3.3 percentage points).

Heating problems causing households to be uncomfortably cold for at least a day were more common for renter-occupied units (by 2.7 percentage points). Renters were also more likely to experience sanitation problems barely reported by owners. This includes having a public sewer breakdown or having no working toilets at some point in the last three months.

Owners were slightly more likely to recently experience a blown fuse or breaker.

### External Building Conditions

The following table shows the number of units experiencing external building problems. This table is limited to single-unit homes, excluding multi-unit homes. Homes with more than one unit are significantly more likely to be renter-occupied. As such, approximately 106,400 rental units were excluded from this table.

+--------------------------------------------------------+----------+-----------+---+---------+---------+
|                                                        | **Rent** |           |   | **Own** |         |
+--------------------------------------------------------+----------+-----------+---+---------+---------+
| **External Building Conditions**                       | **Est**  | **Pct**   |   | **Est** | **Pct** |
+--------------------------------------------------------+----------+-----------+---+---------+---------+
| Bars on windows                                        | 16.1     | **16.7%** |   | 22.0    | 7.7%    |
+--------------------------------------------------------+----------+-----------+---+---------+---------+
| Broken windows                                         | 7.6      | **6.5%**  |   | 7.8     | 2.7%    |
+--------------------------------------------------------+----------+-----------+---+---------+---------+
| Missing roofing material                               | 7.0      | **6.0%**  |   | 15.5    | 5.4%    |
+--------------------------------------------------------+----------+-----------+---+---------+---------+
| Hole in roof                                           | 4.2      | **3.6%**  |   | 6.2     | 2.2%    |
+--------------------------------------------------------+----------+-----------+---+---------+---------+
| Missing bricks, siding, or other outside wall material | 3.9      | 3.3%      |   | 9.4     | 3.3%    |
+--------------------------------------------------------+----------+-----------+---+---------+---------+
| Total housing units (excludes multi-units)             | 117.6    | \-        |   | 286.9   | \-      |
+--------------------------------------------------------+----------+-----------+---+---------+---------+

: Source: [American Housing Survey](https://www.census.gov/newsroom/press-releases/2020/2019-american-housing-survey.html) (2019). Estimates in thousands of housing units.

Renters in single-unit homes were significantly more likely to experience external building problems than owner-occupied units, except for missing wall material, which afflicted 3.3% of both renters and owners. Having bars on windows was especially more common in rental homes (by 9.0 percentage points), as well as having broken windows (by 3.8 percentage points). They were also slightly more likely to have roofing issues, such as missing roofing material or having a hole in the roof.

### Summary

Renter-occupied units are more likely than owner-occupied units to experience housing issues, and by wider margins. Of the 19 housing quality issues discussed in the three tables above, only three problems were more likely to be experienced by owner-occupied units, and only by a margin of 0.4 percentage points for each problem. Meanwhile, there were 15 problems more common in renter-occupied units, 13 of which had a margin greater than 0.4 percentage points.
