# Discussion

Code enforcement is the *only* recourse for renters who want to report landlord neglect. However, Memphis code enforcement does not currently categorize or track this data. Instead, this information is shuffled into a miscellaneous category, with duplicates and errors. While the dataset may be updated daily, it is incredibly hard to organize, and the frequency of new cases only makes the job more difficult.

In conversations with other housing researchers, I found I was not alone in my frustrations with this dataset. I have yet to meet someone who established a way to sort through all the data. One researcher who did regularly use the data limits the scope/analysis to individual neighborhoods. There is no currently known way to monitor trends.

As discussed earlier, two comprehensive reports on Memphis code enforcement have called for a strategic system, rather than the reactive one in place. A strategic code enforcement requires regular analysis of existing data, to find trends and identify blind spots. Without a strategy, code enforcement will opt for the reactive system. This leads inspectors to spend a disproportionate amount of time on minor violations instead of ones that impact public health. As stated by @betts2001, "individual efforts, no matter how well intentioned, are by definition *not strategic*." [44]

While I recognize that asking an organization to alter its data entry methods is a big ask, I have a few specific, basic recommendations which would improve 311 data.

1.  Create a new `REQUEST_TYPE` for requests related to private rental/landlord neglect. This would replace at least some of the "Code Miscellaneous" category with more substantive information. It might also encourage more tenant reporting, as tenants know they're placing their complaint with the right agency.
2.  Create a `RESOLUTION_CODE` for duplicates, replacing "JA" and similar. (For instance "DUPE" is used by other cities like [Cincinnati](https://data.cincinnati-oh.gov/Thriving-Neighborhoods/Code-Enforcement/cncm-znd6))
3.  Do not put all information for one case on one row, overwriting old data. Instead, allow each update its own row.
4.  Close out old cases which are clearly no open anymore.
5.  Implement the **HHRS** into the data system. For occupied housing units, categorize hazards using the HHRS.

This small changes can greatly help with future research into housing maintenance problems.

Ultimately, this paper did not end with code enforcement data based on any belief that the agency is the best way to solve maintenance problems. Since the first municipal code enforcement campaign, the policy tool has often been used at the expense of poor people.[@lieb2018] A recent study of code enforcement data found disparities from self-reporting reinforce inequality and biases.[@kontokosta2021] Code enforcement data will be heavily under-reported as long as tenants who report maintenance problems are not guaranteed stable, affordable, healthy housing.

There are real concerns that strict housing code enforcement would worsen housing affordability. I have deliberately avoided discussions around affordability (and thus most of the little planning literature related to code enforcement) from a belief that the health of the tenant should be prioritized over the price of rent. Ultimately, a rent will be divided between a home's maintenance and a landlord's profit. A city that prioritizes healthy housing for tenants is a city where landlords are not allowed to profit from maintenance neglect.

Planner's specialties allow them to regulate the public health, safety, morals, and general welfare. This police power was previously used in the name of slum clearance, and in some ways that mission continues today with crusades on blight. But why is this regulation on public health not extended to current renters, and before homes become blighted? For instance, consider current code enforcement policy that condemns and boards a house if the cost of repairs is more than half the market value of the house. There is no concern given to a tenant's housing stability. Rather than looking to the market value, which will be marked by historical inequities like redlining, why not consider the value to the city for having all of its citizens stably housed? Suddenly, the cost of condemning the home becomes more expensive.

Public housing in America ended due to mismanagement and neglect of maintenance, and yet few people are calling for the end of private rental housing due to the same practices. Perhaps part of the reason public housing ended was the relative ease of monitoring and tracking the neglect. Information on public housing is publicly available; with relative ease I can find a list of what properties are managed by the city, view the agency plan and yearly financial audit which breaks down revenues and expenses. Meanwhile, trying to find such information about the private rental market is nearly impossible. How are we to hold the private rental market accountable if we don't know the extent of the problem?
