# Summary

The link between housing and health has been well established. Modern humans spend a majority of their time indoors, and the condition of their surroundings inevitably impacts their health. Protecting the public health and safety was the first instance of government involvement of housing. Building standards and health codes have long been established to regulate housing conditions. While the quality of new housing has improved overtime, oft overlooked is the quality of existing homes and whether homes are being maintained.

This paper highlights the role of tenure in maintenance neglect and enforcement. If a homeowner requires housing maintenance, they are able to directly contract and hire someone to repair the problem; for financially strapped individuals, a wide range of subsidies and grants exist geared towards home repair, upgrades, and weatherization. If a tenant experiences a maintenance problem, ensuring repairs are completed is out of their control. They are entirely reliant upon the landlord to follow through with repairs.

When a landlord receives rent, the rent is divided between expenditures in the home and profit for themselves. Tenants have no control over how their rent is portioned, it is for the landlord to decide. Tenants in low-rent homes can be particularly at risk; their homes are likely older and require more maintenance, and lower rents means lower profit margins, incentivizing low-rent landlords to neglect maintenance to preserve profits. Unless a landlord lives on the property, tenants are the ones burdened with experiencing the effects of the neglect, while the landlord is able to ignore and forget the problem while continuing to receive an income.

Tenants who persistently remind the landlord of the problem risk damaging their relationship with their landlord, rent increases, or a forced move due to the landlord choosing to sell the property, the extent of the problem requiring the tenant move for repairs to be completed, or eviction as retaliation. Tenants who withhold rent in an attempt to force their landlords to complete repairs are also at risk of eviction. If a landlord opts to ignore a problem, tenants are left in a powerless position with an impossible choice: speak up and risk their housing stability or stay silent and suffer the health consequences of the problem.

<!--# we're okay with making people homeless if they don't pay their rent, but we rarely take away property from LL who don't do their job. Both people may be in violation of the lease, but one party is pursued and another protected at drastically different rates. -->

Tenants experiencing neglect are incentivized to move to a home with a more responsible owner, or to purchase a home and exit the rental market altogether. This, for one, leaves the problem open for future tenants of the home. But increasingly there is not an option for a home that is available, affordable, and in better condition. If a home is affordable and in better condition, the demand will be high and it likely won't be available. If a home is available and in better condition, it is likely more expensive. If a home is available and affordable, the tenant will likely run into the same maintenance issues as their previous home.

The number of people experiencing this dilemma has increased, particularly over the past decade. As a fallout of the Great Recession, many homeowners became renters and homes formerly occupied by owners were converted into rentals. As rent increases have outpaced incomes over the past decade, renters are more likely to be cost burdened than owners, and rents increasingly eat into their ability to save for a down payment. Households can become trapped in rentership, whether they want to rent or not. As the option of homeownership slips away and cost burdenship rises, more renters fall vulnerable to the power dynamics of the rental market.

<!--# Consider two neighbors, Jane and Catherine, both homeowners experiencing the Great Recession. Catherine loses her job during the recession and is no longer able to pay her mortgage. She is forced to sell the home, and the only bids are from out of state investors looking to convert the home into a rental. Feeling she has no other choice, Catherine sells the home, but she is able to stay as a renter. Meanwhile, Jane does not lose her job or her home. Over the next decade, property taxes remain flat but rents rise, far outpacing any gains Catherine sees in income. By 2021, Catherine is paying more for housing than Jane, and she has lost control over how her housing money is spent.-->

Some have argued that code enforcement can further worsen housing affordability. If maintenance regulation increases, landlords will be required to spend more on maintenance and will likely increase rents in order to cover the increased expenses (or in a soft housing market, it can cause landlords to abandon the home). This is probably true.

But is it better to allow blatant exploitation and slumlords to control low-rent housing, while low-income citizens suffer the health consequences? Is it okay to keep having maintenance neglected, allowing homes to deteriorate until they are demolished, further removing homes from the housing stock? Our choice is to have rent increases or fewer homes. Low-income households suffer either way. At least if we enforce maintenance, there may still be homes available for these households to move into. We could always expand rental subsidies and vouchers. But currently our city has opened the door for slumlords to exploit our citizens. We can at least make being a slumlord less profitable, maybe causing fewer landlords to act in such a neglectful manner if they know the city will pursue action against neglect. Unless things change, we will see more slumlords and more people fall victim to their exploitation.

It also has a negative effect on our climate, as landlords are unlikely to weatherize a home or improve its energy efficiency if they are not the ones bearing the cost of utility bills.

Public housing in America ended due to mismanagement and neglect of maintenance, and yet few people are calling for the end of private rental housing due to the same practices. We ended public housing with the expectation that the private housing market would be more efficient, and yet all I see is exploitation and inefficiencies. Perhaps part of the reason public housing ended was the relative ease of monitoring and tracking the neglect. Information on public housing is publicly available; with relative ease I can find a list of what properties are managed by the city, view the agency plan and yearly financial audit which breaks down revenues and expenses. Meanwhile, trying to find such information about the private rental market is nearly impossible. How are we to hold the private rental market accountable if we don't know the extent of the problem?

Memphis recently attempted to initiate a rental registry, which would partially address these problems. Yet this effort was shut down, in part by lobbying from the real estate lobby. It's worth noting that the National Association of Realtors spent more on lobbying in 2020 than any other organization. [@opensecrets2020]

There is already a law protecting tenants from retaliation, but these protections are flimsy. As it stands, we should not expect tenants to report landlord neglect if doing so risks their housing stability. Tenants need a guarantee that there is another place for them to live if they report maintenance problems.

The city should reevaluate it's policy on condemnation. Currently a home is condemned and demolished if the cost of repairs is more than half the market value of the home. But this valuation does not take into account the value brought to a city by having all of its citizens housed. This valuation does not ask if there is an affordable, available, well-maintained home for the displaced person to move. If such a home does not exist, then condemnation objectively makes low-income tenants worse off, and the home may have more value than the market price states.

<!--# (The home does not have to be rebuilt in the same way. For instance, the rehabilitation could add another housing unit to the building, expanding housing options.) -->
