## COVID-19 & Evictions

---

Asthma

The authors concluded that prevention and remediation to reduce indoor dampness is urgently needed in a large proportion of the building stock, and such measures could significantly reduce the prevalence of respiratory and allergic disease.

, and similarly suggested that public health interventions in housing could reduce allergen exposure

Memphis health

leading authors to conclude that effective health interventions should consider involving housing policies and procedures

Maintenance Pvt Mkt

The authors propose a wide range of solutions to improve tenant reporting. Ending no-cause evictions and expanding legal aid can encourage tenants who may be scared to speak up. Increasing the supply of social or public housing can expand housing options to households most vulnerable to changes in rent. The authors also suggest authorities supervise a web-based reporting system for repair requests, establishing clear records, automated reminders to the landlords, and an opportunity for authorities to step in for unduly slow repairs.
